//> macos: define: APPLE_PLATFORM

import "glad/glad.h" as glad;
import "GLFW/glfw3.h" as glfw;
import "cglm/cglm.h" as glm;
import "../../utils/shader_program.zc";
import "../../utils/camera.zc";

fn framebuffer_size_callback(window: glfw::GLFWwindow*
                            , width: int, height: int );
fn mouse_callback(window:glfw::GLFWwindow*, xpos_in: f64, ypos_in: f64);
fn scroll_callback(window: glfw::GLFWwindow*, xoffset: f64, yoffset: f64);
fn process_input(window: glfw::GLFWwindow*);

// settings
def SCREEN_WIDTH: uint = 800;
def SCREEN_HEIGHT: uint = 600;

//camera
let camera: Camera;
let last_x = SCREEN_WIDTH / 2.0f;
let last_y = SCREEN_HEIGHT / 2.0f;
let first_mouse: bool = true;

//timing
let delta_time: f32 = 0.0f;
let last_frame: f32 = 0.0f;

//lighting
let light_pos: glm::vec3 = [1.2f,1.0f,2.0f];


fn _main() -> int {
    // glfw: initiliaze and configure
    // -----------------------------
    glfw::glfwInit();
    defer glfw::glfwTerminate();
    glfw::glfwWindowHint(glfw::GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfw::glfwWindowHint(glfw::GLFW_CONTEXT_VERSION_MINOR, 3);
    glfw::glfwWindowHint(glfw::GLFW_OPENGL_PROFILE, glfw::GLFW_OPENGL_CORE_PROFILE);
    
#ifdef APPLE_PLATFORM
    glfw::glfwWindowHint(glfw::GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
#endif

    // glfw window creation
    // ---------------------
    let window: glfw::GLFWwindow* = glfw::glfwCreateWindow(
        SCREEN_WIDTH
        ,SCREEN_HEIGHT
        ,"LearnOpengl"
        ,NULL
        ,NULL);
    
    if window == NULL {
        eprintln "Failed to create GLFW window";
        return -1; 
    }

    glfw::glfwMakeContextCurrent(window);
    glfw::glfwSetFramebufferSizeCallback(window, framebuffer_size_callback);
    glfw::glfwSetCursorPosCallback(window, mouse_callback);
    glfw::glfwSetScrollCallback(window, scroll_callback);

    //tell GLFW to capture our mouse
    glfw::glfwSetInputMode(window, glfw::GLFW_CURSOR, glfw::GLFW_CURSOR_DISABLED);

    // glad: load all OpenGL function pointers
    // ---------------------------------------
    if !glad::gladLoadGLLoader((glad::GLADloadproc)glfw::glfwGetProcAddress) {
        eprintln "Failed to initialize GLAD";
        return -1;
    }

    // configure global opengl state
    // -----------------------------
    glad::glEnable(glad::GL_DEPTH_TEST);

    // build and compile our shader zprogram
    // ------------------------------------
    let lighting_shader: ShaderProgram = ShaderProgram::new(
        "./shaders/2.lighting/2.1.basic_lighting.vs",
        "./shaders/2.lighting/2.1.basic_lighting.fs"
    ).unwrap();

    let lighting_cube_shader: ShaderProgram = ShaderProgram::new(
        "./shaders/2.lighting/2.1.light_cube.vs",
        "./shaders/2.lighting/2.1.light_cube.fs"
    ).unwrap();  

    // set up vertex data (and buffer(s)) and configure vertex
    // attributes
    def VERTICES_SIZE = 6 * (6 * 6);
    let vertices: f32[VERTICES_SIZE] = [
        -0.5f, -0.5f, -0.5f,  0.0f,  0.0f, -1.0f,
         0.5f, -0.5f, -0.5f,  0.0f,  0.0f, -1.0f,
         0.5f,  0.5f, -0.5f,  0.0f,  0.0f, -1.0f,
         0.5f,  0.5f, -0.5f,  0.0f,  0.0f, -1.0f,
        -0.5f,  0.5f, -0.5f,  0.0f,  0.0f, -1.0f,
        -0.5f, -0.5f, -0.5f,  0.0f,  0.0f, -1.0f,

        -0.5f, -0.5f,  0.5f,  0.0f,  0.0f,  1.0f,
         0.5f, -0.5f,  0.5f,  0.0f,  0.0f,  1.0f,
         0.5f,  0.5f,  0.5f,  0.0f,  0.0f,  1.0f,
         0.5f,  0.5f,  0.5f,  0.0f,  0.0f,  1.0f,
        -0.5f,  0.5f,  0.5f,  0.0f,  0.0f,  1.0f,
        -0.5f, -0.5f,  0.5f,  0.0f,  0.0f,  1.0f,

        -0.5f,  0.5f,  0.5f, -1.0f,  0.0f,  0.0f,
        -0.5f,  0.5f, -0.5f, -1.0f,  0.0f,  0.0f,
        -0.5f, -0.5f, -0.5f, -1.0f,  0.0f,  0.0f,
        -0.5f, -0.5f, -0.5f, -1.0f,  0.0f,  0.0f,
        -0.5f, -0.5f,  0.5f, -1.0f,  0.0f,  0.0f,
        -0.5f,  0.5f,  0.5f, -1.0f,  0.0f,  0.0f,

         0.5f,  0.5f,  0.5f,  1.0f,  0.0f,  0.0f,
         0.5f,  0.5f, -0.5f,  1.0f,  0.0f,  0.0f,
         0.5f, -0.5f, -0.5f,  1.0f,  0.0f,  0.0f,
         0.5f, -0.5f, -0.5f,  1.0f,  0.0f,  0.0f,
         0.5f, -0.5f,  0.5f,  1.0f,  0.0f,  0.0f,
         0.5f,  0.5f,  0.5f,  1.0f,  0.0f,  0.0f,

        -0.5f, -0.5f, -0.5f,  0.0f, -1.0f,  0.0f,
         0.5f, -0.5f, -0.5f,  0.0f, -1.0f,  0.0f,
         0.5f, -0.5f,  0.5f,  0.0f, -1.0f,  0.0f,
         0.5f, -0.5f,  0.5f,  0.0f, -1.0f,  0.0f,
        -0.5f, -0.5f,  0.5f,  0.0f, -1.0f,  0.0f,
        -0.5f, -0.5f, -0.5f,  0.0f, -1.0f,  0.0f,

        -0.5f,  0.5f, -0.5f,  0.0f,  1.0f,  0.0f,
         0.5f,  0.5f, -0.5f,  0.0f,  1.0f,  0.0f,
         0.5f,  0.5f,  0.5f,  0.0f,  1.0f,  0.0f,
         0.5f,  0.5f,  0.5f,  0.0f,  1.0f,  0.0f,
        -0.5f,  0.5f,  0.5f,  0.0f,  1.0f,  0.0f,
        -0.5f,  0.5f, -0.5f,  0.0f,  1.0f,  0.0f
    ];

    //first, configure the cube's VAO and VBO
    let VBO: uint;
    defer glad::glDeleteBuffers(1, &VBO);

    let cube_VAO: uint;
    defer glad::glDeleteVertexArrays(1, &cube_VAO);

    glad::glGenVertexArrays(1, &cube_VAO);
    glad::glGenBuffers(1, &VBO);

    glad::glBindBuffer(glad::GL_ARRAY_BUFFER, VBO);
    glad::glBufferData(
        glad::GL_ARRAY_BUFFER
        , sizeof(vertices)
        , vertices
        , glad::GL_STATIC_DRAW);

    glad::glBindVertexArray(cube_VAO);

    //position attribute
    glad::glVertexAttribPointer(
        0, 3, glad::GL_FLOAT
        , glad::GL_FALSE, 6 * sizeof(f32)
        , (void*)0 
        );
    
    glad::glEnableVertexAttribArray(0);

    //normal attribute
    glad::glVertexAttribPointer(
        1, 3, glad::GL_FLOAT
        ,glad::GL_FALSE, 6 * sizeof(f32)
        ,(void*)(3 * sizeof(f32))
        );
    glad::glEnableVertexAttribArray(1);

    // second, configure the light's VAO (VBO stays the same), the vertices stays the same
    // because the light source its a 3d cube too
    let ligth_cube_VAO: uint;
    defer glad::glDeleteVertexArrays(1, &ligth_cube_VAO);

    glad::glGenVertexArrays(1, &ligth_cube_VAO);
    glad::glBindVertexArray(ligth_cube_VAO);

    glad::glBindBuffer(glad::GL_ARRAY_BUFFER, VBO);
    // note that we update the lamp's position attribute's stride 
    // to reflect the updated buffer data
    glad::glVertexAttribPointer(
        0, 3, glad::GL_FLOAT
        , glad::GL_FALSE, 6 * sizeof(f32)
        ,(void*)0);
    glEnableVertexAttribArray(0);

    let a: glm::vec3 = [0.0f, 0.0f, 3.0f];
    let b: glm::vec3 = [0.0f, 1.0f, 0.0f];
    camera = Camera::new(a,b);

    while !glfw::glfwWindowShouldClose(window) {

        // per-frame time logic
        // --------------------
        let current_frame: f32 = (f32)glfw::glfwGetTime();
        delta_time = current_frame - last_frame;
        last_frame = current_frame;

        // input
        // -----
        process_input(window);

        // render
        // -----
        glad::glClearColor(0.1f, 0.1f, 0.1f, 1.0f);
        glad::glClear(glad::GL_COLOR_BUFFER_BIT | glad::GL_DEPTH_BUFFER_BIT);

        // be sure to activate shader when setting uniforms/drawing objects
        lighting_shader.useProgram();
        let color: glm::vec3 = [1.0f, 0.5f,0.31f];
        lighting_shader.setVec3("objectColor", color);
        let lcolor: glm::vec3 = [1.0f,1.0f,1.0f];
        lighting_shader.setVec3("lightColor", lcolor);
        lighting_shader.setVec3("lightPos", light_pos);

        //  view/projection transformations
        let projection: glm::mat4 = glm::GLM_MAT4_IDENTITY_INIT;
        glm::glm_perspective(
            glm::glm_rad(camera.Zoom),
            (f32)SCREEN_WIDTH / (f32)SCREEN_HEIGHT,
            0.1f,
            100.0f,
            projection
        );

        // camera/view transformation
        let view: glm::mat4 = glm::GLM_MAT4_IDENTITY_INIT;
        camera.get_view_matrix(view);

        lighting_shader.setMat4(
            "projection",
            projection
        );

        // pass transformation matrices to shader
        lighting_shader.setMat4(
            "view",
            view
        );

        // world transformation
        let model: glm::mat4 = glm::GLM_MAT4_IDENTITY_INIT;
        lighting_shader.setMat4("model", model);

        // render the cube
        glad::glBindVertexArray(cube_VAO);
        glad::glDrawArrays(glad::GL_TRIANGLES, 0, 36);

        // also draw the lamp object
        lighting_cube_shader.useProgram();
        lighting_cube_shader.setMat4("projection", projection);
        lighting_cube_shader.setMat4("view", view);
        //model = glm::GLM_MAT4_IDENTITY_INIT;
        glm_mat4_identity(model);
        glm::glm_translate_to(model, light_pos, model);
        let scale: glm::vec3 = [0.2f,0.2f,0.2f];
        glm::glm_scale_to(model,scale,model);
        lighting_cube_shader.setMat4("model",model);

        glad::glBindVertexArray(ligth_cube_VAO);
        glad::glDrawArrays(glad::GL_TRIANGLES, 0, 36);

        // glfw: swap buffers and poll IO events
        glfw::glfwSwapBuffers(window);
        glfw::glfwPollEvents();

    }

    // the cleaning its done via defer calls
    return 0;

}

// glfw: whenever the window size changed (by OS or user resize)
// this callback is called
fn framebuffer_size_callback(window: glfw::GLFWwindow*
                            , width: int, height: int ) {
    glad::glViewport(0,0, width, height);
}

// glfw: whenever the mouse moves, this callback is called
fn mouse_callback(window:glfw::GLFWwindow*, xpos_in: f64, ypos_in: f64) {
    let xpos: f32 = (f32)xpos_in;
    let ypos: f32 = (f32)ypos_in;

    if first_mouse {
        last_x = xpos;
        last_y = ypos;
        first_mouse = false;
    }
    let x_offset: f32 = xpos - last_x;
    let y_offset: f32 = last_y - ypos;

    last_x = xpos;
    last_y = ypos;

    camera.process_mouse_movement(x_offset, y_offset, true);

}

fn scroll_callback(window: glfw::GLFWwindow*, xoffset: f64, yoffset: f64) {
    camera.process_mouse_scroll((f32)yoffset);
}


fn process_input(window: glfw::GLFWwindow*) {
    if glfw::glfwGetKey(window, glfw::GLFW_KEY_ESCAPE) == glfw::GLFW_PRESS {
        glfw::glfwSetWindowShouldClose(window, true);
    }

    if glfw::glfwGetKey(window, glfw::GLFW_KEY_W) == glfw::GLFW_PRESS {
        camera.process_keyboard(CameraMovement::FORWARD, delta_time);
    }
    if glfw::glfwGetKey(window, glfw::GLFW_KEY_S) == glfw::GLFW_PRESS {
        camera.process_keyboard(CameraMovement::BACKWARD, delta_time);
    }
    if glfw::glfwGetKey(window, glfw::GLFW_KEY_A) == glfw::GLFW_PRESS {
        camera.process_keyboard(CameraMovement::LEFT, delta_time);
    }
    if glfw::glfwGetKey(window, glfw::GLFW_KEY_D) == glfw::GLFW_PRESS {
        camera.process_keyboard(CameraMovement::RIGHT, delta_time);
    }

}
