import "glad/glad.h" as glad;
import "GLFW/glfw3.h" as glfw;
import "../../utils/shader_program.zc";
import "stb_image.h" as stb;
import "cglm/cglm.h" as glm;           
import "cglm/affine.h" as glm;        // translate, rotate, etc.
//import "cglm/cam.h" as glm;
import "std/math.zc";

// settings
def SCREEN_WIDTH: uint = 800;
def SCREEN_HEIGHT: uint = 600;

// forward declarations
fn framebuffer_size_callback(window: glfw::GLFWwindow*, width: int, height: int);
fn mouse_callback(window: glfw::GLFWwindow*, xpos_in: f64, ypos_in: f64);
fn scroll_callback(window: glfw::GLFWwindow*, xoffset: f64, yoffset: f64);
fn process_input(window: glfw::GLFWwindow*);

let camera_pos: glm::vec3 = [0.0f, 0.0f, 3.0f];
let camera_front: glm::vec3 = [0.0f,0.0f,-1.0f];
let camera_up: glm::vec3 = [0.0f,1.0f,0.0f];

let first_mouse: bool = true;
let yaw: f32 = -90.0f;
let pitch: f32 = 0.0f;
let last_x: f32 = SCREEN_WIDTH/2.0;
let last_y: f32 = SCREEN_HEIGHT/2.0;
let fov: f32 = 45.0f;

let delta_time: f32 = 0.0f;
let last_frame: f32 = 0.0f;

fn _main() -> int {
    println "[1] CPU: Program start";
    // Entry point of the application (runs on CPU)

    
    // =========================
    // CPU → CONTEXT SETUP
    // =========================

    println "[2] CPU: Initializing GLFW";
    // Initializes the window system and prepares OpenGL usage
    glfw::glfwInit();
    defer glfw::glfwTerminate();

    println "[3] CPU: Configuring OpenGL context (3.3 core)";
    // Tells GLFW which OpenGL version we want to use
    glfw::glfwWindowHint(glfw::GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfw::glfwWindowHint(glfw::GLFW_CONTEXT_VERSION_MINOR, 3);
    glfw::glfwWindowHint(glfw::GLFW_OPENGL_PROFILE, glfw::GLFW_OPENGL_CORE_PROFILE);

    println "[4] CPU: Creating window + OpenGL context";
    // Creates a window AND an OpenGL context attached to it
    let window = glfw::glfwCreateWindow(
        SCREEN_WIDTH,
        SCREEN_HEIGHT,
        "LearnOpenGL",
        NULL,
        NULL
    );

    if window == NULL {
        eprintln "Failed to create GLFW window";
        return -1;
    }

    println "[5] CPU: Making context current";
    // Makes this window's OpenGL context the active one on this thread
    glfw::glfwMakeContextCurrent(window);

    // Registers a callback that updates the viewport when window resizes
    glfw::glfwSetFramebufferSizeCallback(window, framebuffer_size_callback);
    glfw::glfwSetCursorPosCallback(window,mouse_callback);
    glfw::glfwSetScrollCallback(window, scroll_callback);

    glfw::glfwSetInputMode(window, glfw::GLFW_CURSOR, glfw::GLFW_CURSOR_DISABLED);

    println "[6] CPU → DRIVER: Loading OpenGL functions (GLAD)";
    // GLAD loads function pointers for OpenGL (because OpenGL is driver-dependent)
    if glad::gladLoadGLLoader((glad::GLADloadproc)glfw::glfwGetProcAddress) == 0 {
        eprintln "Failed to initialize GLAD";
        return -1;
    }

    glad::glEnable(glad::GL_DEPTH_TEST);

    let our_shader = ShaderProgram::new("./shaders/6.2.coordinate_systems_depth/6.2.shader.vs","./shaders/6.2.coordinate_systems_depth/6.2.shader.fs").unwrap();
    

    // =========================
    // INPUT ASSEMBLER (GEOMETRY)
    // =========================

    println "[17] CPU: Defining vertex + index data";
    // Define geometry on CPU (positions of points)

    let vertices: const f32[180] = [
        -0.5f, -0.5f, -0.5f,  0.0f, 0.0f,
         0.5f, -0.5f, -0.5f,  1.0f, 0.0f,
         0.5f,  0.5f, -0.5f,  1.0f, 1.0f,
         0.5f,  0.5f, -0.5f,  1.0f, 1.0f,
        -0.5f,  0.5f, -0.5f,  0.0f, 1.0f,
        -0.5f, -0.5f, -0.5f,  0.0f, 0.0f,

        -0.5f, -0.5f,  0.5f,  0.0f, 0.0f,
         0.5f, -0.5f,  0.5f,  1.0f, 0.0f,
         0.5f,  0.5f,  0.5f,  1.0f, 1.0f,
         0.5f,  0.5f,  0.5f,  1.0f, 1.0f,
        -0.5f,  0.5f,  0.5f,  0.0f, 1.0f,
        -0.5f, -0.5f,  0.5f,  0.0f, 0.0f,

        -0.5f,  0.5f,  0.5f,  1.0f, 0.0f,
        -0.5f,  0.5f, -0.5f,  1.0f, 1.0f,
        -0.5f, -0.5f, -0.5f,  0.0f, 1.0f,
        -0.5f, -0.5f, -0.5f,  0.0f, 1.0f,
        -0.5f, -0.5f,  0.5f,  0.0f, 0.0f,
        -0.5f,  0.5f,  0.5f,  1.0f, 0.0f,

         0.5f,  0.5f,  0.5f,  1.0f, 0.0f,
         0.5f,  0.5f, -0.5f,  1.0f, 1.0f,
         0.5f, -0.5f, -0.5f,  0.0f, 1.0f,
         0.5f, -0.5f, -0.5f,  0.0f, 1.0f,
         0.5f, -0.5f,  0.5f,  0.0f, 0.0f,
         0.5f,  0.5f,  0.5f,  1.0f, 0.0f,

        -0.5f, -0.5f, -0.5f,  0.0f, 1.0f,
         0.5f, -0.5f, -0.5f,  1.0f, 1.0f,
         0.5f, -0.5f,  0.5f,  1.0f, 0.0f,
         0.5f, -0.5f,  0.5f,  1.0f, 0.0f,
        -0.5f, -0.5f,  0.5f,  0.0f, 0.0f,
        -0.5f, -0.5f, -0.5f,  0.0f, 1.0f,

        -0.5f,  0.5f, -0.5f,  0.0f, 1.0f,
         0.5f,  0.5f, -0.5f,  1.0f, 1.0f,
         0.5f,  0.5f,  0.5f,  1.0f, 0.0f,
         0.5f,  0.5f,  0.5f,  1.0f, 0.0f,
        -0.5f,  0.5f,  0.5f,  0.0f, 0.0f,
        -0.5f,  0.5f, -0.5f,  0.0f, 1.0f
    ];
        // world space positions of our cubes
    let cube_positions: f32[10][3] = [
        [ 0.0f,  0.0f,  0.0f ],
        [ 2.0f,  5.0f, -15.0f ],
        [-1.5f, -2.2f, -2.5f ],
        [-3.8f, -2.0f, -12.3f ],
        [ 2.4f, -0.4f, -3.5f ],
        [-1.7f,  3.0f, -7.5f ],
        [ 1.3f, -2.0f, -2.5f ],
        [ 1.5f,  2.0f, -2.5f ],
        [ 1.5f,  0.2f, -1.5f ],
        [-1.3f,  1.0f, -1.5f ]
    ];

    let VBO: uint;
    defer glad::glDeleteBuffers(1, &VBO);
    let VAO: uint;
    defer glad::glDeleteVertexArrays(1, &VAO);

    println "[18] CPU → GPU: Creating buffers (VAO, VBO)";
    // Ask GPU to allocate memory for vertex data
    glad::glGenVertexArrays(1,&VAO);
    glad::glGenBuffers(1,&VBO);

    println "[19] INPUT ASSEMBLER: Binding VAO (captures state)";
    // VAO stores how vertex data is configured
    glad::glBindVertexArray(VAO);

    println "[20] INPUT ASSEMBLER: Uploading vertex buffer (VBO)";
    // Send vertex data to GPU memory
    glad::glBindBuffer(glad::GL_ARRAY_BUFFER, VBO);
    glad::glBufferData(glad::GL_ARRAY_BUFFER, sizeof(vertices),vertices,glad::GL_STATIC_DRAW);
    
    println "[22] INPUT ASSEMBLER: Defining vertex layout (attribute 0)";
    // Tell GPU how to interpret the raw vertex data
    // position attribute
    glad::glVertexAttribPointer(0, 3, glad::GL_FLOAT, glad::GL_FALSE, 5 * sizeof(f32), (void*)0);
    glad::glEnableVertexAttribArray(0);

    // Tell GPU how to interpret the raw vertex data
    //// texture coord attribute
    glad::glVertexAttribPointer(1, 2, glad::GL_FLOAT, glad::GL_FALSE, 5 * sizeof(f32), (void*)(3 * sizeof(f32)));
    glad::glEnableVertexAttribArray(1);

    // load and create a texture 
    // -------------------------
    let texture01: uint;
    glad::glGenTextures(1,&texture01);
    glad::glBindTexture(glad::GL_TEXTURE_2D, texture01);
    glad::glTexParameteri(glad::GL_TEXTURE_2D, glad::GL_TEXTURE_WRAP_S, glad::GL_REPEAT);
    glad::glTexParameteri(glad::GL_TEXTURE_2D, glad::GL_TEXTURE_WRAP_T, glad::GL_REPEAT);
    glad::glTexParameteri(glad::GL_TEXTURE_2D, glad::GL_TEXTURE_MIN_FILTER, glad::GL_LINEAR_MIPMAP_LINEAR);
    glad::glTexParameteri(glad::GL_TEXTURE_2D, glad::GL_TEXTURE_MAG_FILTER, glad::GL_LINEAR);

    let texture_width01: int;
    let texture_height01: int;
    let texture_nr_channels01: int;

    let texture_data01: c_uchar* = stb::stbi_load("textures/container.jpg",&texture_width01,&texture_height01,&texture_nr_channels01,0);

    if texture_data01 != NULL {
        glad::glTexImage2D(
            glad::GL_TEXTURE_2D,
            0,
            glad::GL_RGB,
            texture_width01,
            texture_height01,
            0,
            glad::GL_RGB,
            glad::GL_UNSIGNED_BYTE,
            texture_data01
        );
        glad::glGenerateMipmap(glad::GL_TEXTURE_2D);
    } else {
        eprintln "Failed to load texture 01";
    }

    stb::stbi_image_free(texture_data01);

    // load and create a texture 
    // -------------------------
    let texture02: uint;
    glad::glGenTextures(1,&texture02);
    glad::glBindTexture(glad::GL_TEXTURE_2D, texture02);
    glad::glTexParameteri(glad::GL_TEXTURE_2D, glad::GL_TEXTURE_WRAP_S, glad::GL_REPEAT);
    glad::glTexParameteri(glad::GL_TEXTURE_2D, glad::GL_TEXTURE_WRAP_T, glad::GL_REPEAT);
    glad::glTexParameteri(glad::GL_TEXTURE_2D, glad::GL_TEXTURE_MIN_FILTER, glad::GL_LINEAR);
    glad::glTexParameteri(glad::GL_TEXTURE_2D, glad::GL_TEXTURE_MAG_FILTER, glad::GL_LINEAR);

    let texture_width02: int;
    let texture_height02: int;
    let texture_nr_channels02: int;

    stb::stbi_set_flip_vertically_on_load(true); 
    let texture_data02: c_uchar* = stb::stbi_load("textures/awesomeface.png",&texture_width02,&texture_height02,&texture_nr_channels02,0);

    if texture_data02 != NULL {
        glad::glTexImage2D(
            glad::GL_TEXTURE_2D,
            0,
            glad::GL_RGBA,
            texture_width02,
            texture_height02,
            0,
            glad::GL_RGBA,
            glad::GL_UNSIGNED_BYTE,
            texture_data02
        );
        glad::glGenerateMipmap(glad::GL_TEXTURE_2D);
    } else {
        eprintln "Failed to load texture 02";
    }

    stb::stbi_image_free(texture_data02);
    
    our_shader.useProgram();
    glad::glUniform1i(glad::glGetUniformLocation(our_shader.ID,"texture01"),0);
    our_shader.setInt("texture02",1);

    println "[23] CPU: Unbinding VBO";
    // Safe to unbind because VAO already stored the configuration
    glad::glBindBuffer(glad::GL_ARRAY_BUFFER, 0); 

    println "[24] CPU: Unbinding VAO";
    glad::glBindVertexArray(0); 

    println "[25] RASTERIZER CONFIG: Wireframe mode enabled";

    println "[26] Setup complete → entering render loop";
    // From now on, we repeatedly draw frames




    // render loop
    while glfw::glfwWindowShouldClose(window) == 0 {
        // per-frame time logic
        // --------------------
        let current_frame: f32 = (f32)glfw::glfwGetTime();
        delta_time = current_frame - last_frame;
        last_frame = current_frame;
        
        process_input(window);

        glad::glClearColor(0.2f,0.3f,0.3f,1.0f);
        glad::glClear(glad::GL_COLOR_BUFFER_BIT | glad::GL_DEPTH_BUFFER_BIT);

        // =========================
        // GPU PIPELINE EXECUTION
        // =========================

        glad::glActiveTexture(glad::GL_TEXTURE0);
        glad::glBindTexture(glad::GL_TEXTURE_2D, texture01);
        glad::glActiveTexture(glad::GL_TEXTURE1);
        glad::glBindTexture(glad::GL_TEXTURE_2D, texture02);

        // [27] Select shader program (GPU will use it)
        our_shader.useProgram();

        // pass projection matrix to shader (as projection matrix rarely changes there's no need to do this per frame)
        // -----------------------------------------------------------------------------------------------------------
        let projection: glm::mat4 = glm::GLM_MAT4_IDENTITY_INIT;
        glm::glm_perspective(
            glm::glm_rad(fov),
            (f32)SCREEN_WIDTH / (f32)SCREEN_HEIGHT,
            0.1f,
            100.0f,
            projection
        );
        our_shader.setMat4(
            "projection",
            projection
        );

        // camera/view transformation
        let view: glm::mat4 = glm::GLM_MAT4_IDENTITY_INIT;

        let dest: glm::vec3 = [0.0f,0.0f,0.0f];
        glm::glm_vec3_add(camera_pos,camera_front,dest);
        glm::glm_lookat(camera_pos,dest,camera_up,view);

        // view = translate(view, vec3(0,0,-3))


        //let camera_translation: glm::vec3 = [
        //    0.0f,
        //    0.0f,
        //    -3.0f
        //];
//
        //glm::glm_translate(
        //    view,
        //    camera_translation
        //);

        // pass transformation matrices to shader


        our_shader.setMat4(
            "view",
            view
        );

        // render boxes

        glad::glBindVertexArray(VAO);

        for i in 0..(sizeof(cube_positions) / sizeof(cube_positions[0])) {

            // model matrix

            let model: glm::mat4 = glm::GLM_MAT4_IDENTITY_INIT;

            // model = translate(model, cubePositions[i])

            glm::glm_translate(
                model,
                cube_positions[i]
            );

            // float angle = 20.0f * i;

            let angle = 20.0f * ((f32)i);

            // model = rotate(model, radians(angle), axis)

            let rotation_axis: glm::vec3 = [
                1.0f,
                0.3f,
                0.5f
            ];

            glm::glm_rotate(
                model,
                glm::glm_rad(angle),
                rotation_axis
            );

            // send model matrix

            our_shader.setMat4(
                "model",
                model
            );

            // draw cube

            glad::glDrawArrays(
                glad::GL_TRIANGLES,
                0,
                36
            );
        }
        
        glfw::glfwSwapBuffers(window);
        glfw::glfwPollEvents();
    }

    println "[30] CPU: Program terminated";
    return 0;
}

// input
fn process_input(window: glfw::GLFWwindow*) {
    if glfw::glfwGetKey(window, glfw::GLFW_KEY_ESCAPE) == glfw::GLFW_PRESS {
        println "[INPUT] ESC pressed → closing window";
        glfw::glfwSetWindowShouldClose(window, true);
    }

    let camera_speed: f32 = (f32)(2.5 * delta_time);
    if glfw::glfwGetKey(window, glfw::GLFW_KEY_W) == glfw::GLFW_PRESS {
        println "[INPUT] W pressed";
        glm::glm_vec3_muladds(camera_front,camera_speed,camera_pos);
    }
    if glfw::glfwGetKey(window, glfw::GLFW_KEY_S) == glfw::GLFW_PRESS {
        println "[INPUT] S pressed";
        glm::glm_vec3_muladds(camera_front,-camera_speed,camera_pos);
    }
    if glfw::glfwGetKey(window, glfw::GLFW_KEY_A) == glfw::GLFW_PRESS {
        println "[INPUT] A pressed";
        let cross: glm::vec3 = [0.0f, 0.0f,0.0f];
        glm::glm_vec3_cross(camera_front, camera_up,cross);
        glm::glm_vec3_normalize(cross);
        glm::glm_vec3_muladds(cross,-camera_speed,camera_pos);
    }
    if glfw::glfwGetKey(window, glfw::GLFW_KEY_D) == glfw::GLFW_PRESS {
        println "[INPUT] D pressed";
        let cross: glm::vec3 ;
        glm::glm_vec3_cross(camera_front, camera_up,cross);
        glm::glm_vec3_normalize(cross);
        glm::glm_vec3_muladds(cross,camera_speed,camera_pos);
    }
}

// resize callback
fn framebuffer_size_callback(_window: glfw::GLFWwindow*, width: int, height: int) {
    println "[CALLBACK] Viewport updated";
    // Updates the drawable area of the window
    glad::glViewport(0, 0, width, height);
}

fn mouse_callback(window: glfw::GLFWwindow*, xpos_in: f64, ypos_in: f64) {
    /*
    float xpos = static_cast<float>(xposIn);
    float ypos = static_cast<float>(yposIn);

    if (firstMouse)
    {
        lastX = xpos;
        lastY = ypos;
        firstMouse = false;
    }

    float xoffset = xpos - lastX;
    float yoffset = lastY - ypos; // reversed since y-coordinates go from bottom to top
    lastX = xpos;
    lastY = ypos;

    float sensitivity = 0.1f; // change this value to your liking
    xoffset *= sensitivity;
    yoffset *= sensitivity;

    yaw += xoffset;
    pitch += yoffset;

    // make sure that when pitch is out of bounds, screen doesn't get flipped
    if (pitch > 89.0f)
        pitch = 89.0f;
    if (pitch < -89.0f)
        pitch = -89.0f;

    glm::vec3 front;
    front.x = cos(glm::radians(yaw)) * cos(glm::radians(pitch));
    front.y = sin(glm::radians(pitch));
    front.z = sin(glm::radians(yaw)) * cos(glm::radians(pitch));
    cameraFront = glm::normalize(front);
}
    */
    let xpos = (f32)xpos_in;
    let ypos = (f32)ypos_in;

    if first_mouse {
        last_x = xpos;
        last_y = ypos;
        first_mouse = false;
    }

    let x_offset = xpos - last_x;
    let y_offset = last_y - ypos;
    last_x = xpos;
    last_y = ypos;

    let sensivity: f32 = 0.1f;
    x_offset *= sensivity;
    y_offset *= sensivity;

    yaw += x_offset;
    pitch += y_offset;

    if pitch > 89.0f {
        pitch = 89.0f;
    }
    if pitch < -89.0f {
        pitch = -89.0f;
    }

    let front: glm::vec3 = [0.0f, 0.0f,0.0f];
    front[0] = Math::cos(glm::glm_rad(yaw)) * Math::cos(glm::glm_rad(pitch));
    front[1] = Math::sin(glm::glm_rad(pitch))
    front[2] = Math::sin(glm::glm_rad(yaw)) * Math::cos(glm::glm_rad(pitch));
    glm::glm_vec3_normalize_to(front,camera_front);
}

fn scroll_callback(window: glfw::GLFWwindow*, xoffset: f64, yoffset: f64) {
    fov -= yoffset;
    if fov < 1.0f {
        fov = 1.0f;
    }
    if fov > 45.0f {
        fov = 45.0f;
    }
}