//> include: ./libs/glad/include ./libs/glfw/include
//> lib: ./libs/glfw/lib 
//> link: ./libs/glad/src/glad.c -lglfw3 -lopengl32 -lgdi32 -luser32 -lkernel32 -lshell32 -o build/app.exe
// shell: copy /Y .\libs\sdl3\x86_64-w64-mingw32\bin\*.dll .\build\

//import "./1-getting-started/1.2.hello_window_clear/hello_window_clear.zc";
//import "./1-getting-started/2.1.hello_triangle/hello_triangle.zc";
import "./1-getting-started/2.2.hello_triangle_indexed/hello_triangle_indexed.zc"

fn main() {
    _main();
}
